name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Index Re-up
        run: |
          helm package deploy/*
          helm repo index --url https://fzebib.github.io/porkbun-webhook/ .


      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Firas
          author_email: fzebib@gmail.com
          message: 'index update'
          add: 'index.yaml'

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: deploy
